```{r setup, echo=FALSE, results='hide'}
# setup
opts_chunk$set(message=FALSE, warning=FALSE, background='#F7F7F7', dpi=100, fig.align='center', dev='CairoPNG', tidy=TRUE, verbose=FALSE)
options(width=100, stringsAsFactors=FALSE)
```

## Working with gSSURGO and SDA
2013-03-15
Dylan Beaudette


### Installation
With a recent version of R, it should be possible to get all of the packages need for this tutorial via:
```{r ssoap-deps, eval=FALSE}
# run these commands in the R console
install.packages('soilDB', dep=TRUE) # stable version from CRAN + dependencies
install.packages("soilDB", repos="http://R-Forge.R-project.org") # most recent copy from r-forge
install.packages("SSOAP", repos = "http://www.omegahat.org/R", type="source") # SSOAP and XMLSchema
```


### Example Code
```{r, results='hide'}
# load libraries
library(Hmisc)
library(soilDB)
library(plyr)
library(raster)


# function for computing profile-total water storage
co.sum.whc <- function(i) {
	wt <- i$comppct_r[1] # keep the first component pct (they are all the same)
	thick <- with(i, hzdepb_r - hzdept_r) # compute horizon thickness
	whc <- thick * i$awc_r # compute water storage by horizon
	whc.total <- sum(whc, na.rm=TRUE) # sum to get profile water storage
	data.frame(whc=whc.total, wt=wt) # return profile water storage and component pct
}

# function for copmuting weighted-mean whc within a map unit
mu.mean.whc <- function(i) {
	whc <- wtd.mean(i$whc, weights=i$wt) # safely compute wt. mean water storage
	data.frame(whc=whc) # return wt. mean water storage
}


# load chunk of gSSURGO, ignoring existing RAT
data(gSSURGO.chunk, package='soilDB')

# convert into a raster + RAT
gSSURGO.chunk <- ratify(gSSURGO.chunk, count=TRUE)

# save RAT to new object, will use later
rat <- levels(gSSURGO.chunk)[[1]]

# extract the map unit kets from the RAT, and format for use in an SQL IN-statement
in.statement <- format_SQL_in_statement(rat$ID)

# format query in SQL- raw data are returned
q <- paste("SELECT component.mukey, component.cokey, compname, comppct_r, hzdept_r, hzdepb_r, hzname, awc_r
FROM component JOIN chorizon ON component.cokey = chorizon.cokey
AND mukey IN ", in.statement, "ORDER BY mukey, comppct_r DESC, hzdept_r ASC", sep="")

# now get component and horizon-level data for these map unit keys
res <- SDA_query(q)

# aggregate by component, retaining map unit keys
co.whc <- ddply(res, c('mukey', 'cokey'), co.sum.whc)

# aggregate by map unit
mu.whc <- ddply(co.whc, 'mukey', mu.mean.whc)

# change first colum name from 'mukey' to 'ID', so that it matches our RAT
names(mu.whc)[1] <- 'ID'

# join
rat.new <- join(rat, mu.whc, type='left')

# save back modified rat
levels(gSSURGO.chunk) <- rat.new

# convert into standard raster based on new column
r.new <- deratify(gSSURGO.chunk, att='whc')

# check: OK
plot(r.new)
```
