---
output:
  html_document:
    mathjax: null
    jquery: null
    smart: no
    self_contained: no
---

## Setup an ODBC Connection to the Local NASIS Database
NASIS 6.2
`r format(Sys.time(), "%Y-%m-%d")`
DEB

### Introduction
This document describes how setup an ODBC link between a local NASIS database and **R**, so that pedon and DMU records can be queried with the [soilDB](https://r-forge.r-project.org/scm/viewvc.php/*checkout*/docs/soilDB/soilDB-Intro.html?root=aqp) package.


### Open the ODBC Data Source Administrator
 1. Windows 7: Start->search for 'OBCC'. See [this page](http://msdn.microsoft.com/en-us/library/ms188691.aspx) for details. 
 
 2. Windows XP: Start->Run, then paste in `odbccp32.cpl` and hit enter. This will open a small panel of ODBC connections. 
 
 3. With the "User DSN" tab selected, create a new data source by clicking on the "Add..." button. 


**Step by Step:**
 * Select the "SQL Server Native Client" driver.
 * Name the data source `nasis_local`, the data source description is optional.
 * The server location is `XXXXXX\NASISSQLEXPRESS`, where `XXXXXX` is the [full name of your local machine](http://windows.microsoft.com/en-us/windows7/find-your-computer-name). It is usually on the outside of your computer somewhere, or can be accessed by right-clicking on the "My Computer" icon and then clicking on the "Properties" tab. It will look something like: `CASONORA00L354`. When finished click "Next".

* Choose the second option: "SQL Server authentication...":
* login: `NASISSQLRO`
* password: `nasisRe@d0n1y`
* On the next screen, select "Nasis-local" as the default data base.
* Click "Next" and then "Finish" the finalize the connection.


### Example
```{r example, eval=FALSE}
# install packages (only first time)
install.packages("RODBC", dep=TRUE) # stable version from CRAN + dependencies
install.packages("soilDB", dep=TRUE) # stable version from CRAN + dependencies

# load the library
library(soilDB)

# fetch all pedons from the local database
fp <- fetchNASIS()

# fetch all DMU records from the local database
fc <- fetchNASIS_component_data()

# access the online manual
help(soilDB)
```

